# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# This is used to exclude rules from the convert
data exclusionRuleList
{
    ConvertFrom-StringData -StringData @'
        V-73523  = ''
        V-6599   = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6600   = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6601   = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6602   = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6604   = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6611   = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6612   = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6614   = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6615   = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6616   = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6617   = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6618   = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6620   = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6625   = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-6627   = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-14657  = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-14658  = 'McAfee: Not Applicable to 64-bit systems.'
        V-14659  = 'McAfee: Not Applicable to 64-bit systems.'
        V-14660  = 'McAfee: Not Applicable to 64-bit systems.'
        V-14661  = 'McAfee: Not Applicable to 64-bit systems.'
        V-42563  = 'McAfee:exclusions have been documented with, and approved by, the ISSO/ISSM/DAA'
        V-42564  = 'McAfee:exclusions have been documented with, and approved by, the ISSO/ISSM/DAA'
        V-42565  = 'McAfee:with the assistance of the System Administrator, review each GUID key's szTaskName'
        V-42566  = 'McAfee:with the assistance of the System Administrator, review each GUID key's szTaskName'
        V-42567  = 'McAfee:with the assistance of the System Administrator, review each GUID key's szTaskName'
        V-42572  = 'McAfee:If the ExcludedURLs REG_MULTI_SZ has any entries, and the excluded URLs have not been documented with, and approved by, the ISSO/ISSM/DAA'
        V-14654  = 'McAfee:The GUID of the weekly on-demand client scan task varies by system'
        V-71933  = 'RHEL: At present, unable to automate rule'
        V-71943  = 'RHEL: At present, unable to automate rule'
        V-71945  = 'RHEL: At present, unable to automate rule'
        V-72049  = 'RHEL: At present, unable to automate rule'
        V-72051  = 'RHEL: At present, unable to automate rule'
        V-72217  = 'RHEL: At present, unable to automate rule'
        V-72223  = 'RHEL: At present, unable to automate rule'
        V-72227  = 'RHEL: At present, unable to automate rule'
        V-72229  = 'RHEL: At present, unable to automate rule'
        V-72269  = 'RHEL: At present, unable to automate rule'
        V-72283  = 'RHEL: At present, unable to automate rule'
        V-72285  = 'RHEL: At present, unable to automate rule'
        V-72287  = 'RHEL: At present, unable to automate rule'
        V-72289  = 'RHEL: At present, unable to automate rule'
        V-72291  = 'RHEL: At present, unable to automate rule'
        V-72293  = 'RHEL: At present, unable to automate rule'
        V-72309  = 'RHEL: At present, unable to automate rule'
        V-72317  = 'RHEL: At present, unable to automate rule'
        V-72319  = 'RHEL: At present, unable to automate rule'
        V-72427  = 'RHEL: At present, unable to automate rule'
        V-73175  = 'RHEL: At present, unable to automate rule'
        V-77819  = 'RHEL: At present, unable to automate rule'
        V-77825  = 'RHEL: At present, unable to automate rule'
        V-81005  = 'RHEL: At present, unable to automate rule'
        V-81007  = 'RHEL: At present, unable to automate rule'
        V-92251  = 'RHEL: At present, unable to automate rule'
        V-92253  = 'RHEL: At present, unable to automate rule'
        V-94843  = 'RHEL: At present, unable to automate rule'
        V-94509  = 'Vsphere: To Be added in a future release'
        V-94025  = 'Vsphere: To Be added in a future release'
        V-94533  = 'Vsphere: To Be added in a future release'
        V-100587 = 'Ubuntu: To be added in a future release'
        V-100591 = 'Ubuntu: To be added in a future release'
        V-100599 = 'Ubuntu: To be added in a future release'
        V-100603 = 'Ubuntu: To be added in a future release'
        V-100615 = 'Ubuntu: To be added in a future release'
        V-100617 = 'Ubuntu: To be added in a future release'
        V-100649 = 'Ubuntu: To be added in a future release'
        V-100853 = 'Ubuntu: To be added in a future release'
        V-100855 = 'Ubuntu: To be added in a future release'
        V-100863 = 'Ubuntu: To be added in a future release'
        V-100875 = 'Ubuntu: Unable to automate rule'
        V-100879 = 'Ubuntu: To be added in a future release'
'@
}
