# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

<#
    This is used to centralize the regEx patterns, note that the backslashes are
    escaped, a single "\s" would be represented as "\\s"
#>
data regularExpression
{
    ConvertFrom-StringData -StringData @'
        nxFileLineContainsLine        = .*\\n(?<setting>.*\\n|.*\\n.*\\n|.*\\n.*\\n.*\\n|.*\\n.*\\n.*\\n.*\\n|.*\\n.*\\n.*\\n.*\\n.*\\n)If.*this is a finding
        nxFileLineContainsLineExclude = The result must contain the following line:|If\\s+.*commented\\s+(?:out|line).*
        nxFileLineFilePath            = #.*\\s(?<filePath>\\/[\\w.\\/-]*\\/[\\w.\\/-]*)
'@
}

<#
    The doesNotContainPattern variable is used by Get-nxFileLineDoesNotContainPattern
#>
data doesNotContainPattern
{
    @{
        'active = yes'                                              = '\s*active\s*=\s*no|active=yes|#\s*active\s*=.*'
        'Unattended-Upgrade::Remove-Unused-Dependencies "true";'    = '\s*Unattended-Upgrade::Remove-Unused-Dependencies\s*("false"|false|true).*|#\s*Unattended-Upgrade::Remove-Unused-Dependencies.*'
        'Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";' = '\s*Unattended-Upgrade::Remove-Unused-Kernel-Packages\s*("false"|false|true).*|#\s*Unattended-Upgrade::Remove-Unused-Kernel-Packages.*'
        'session required pam_lastlog.so showfailed'                = '\s*session\s*(?!required)\w*\s*pam_lastlog\.so.*|#\s*session\s*\w*\s*pam_lastlog\.so.*'
        'ucredit=-1'                                                = '^\s*ucredit\s*=\s*(?!-1)\d*$|#\s*ucredit=.*'
        'lcredit=-1'                                                = '^\s*lcredit\s*=\s*(?!-1)\d*$|#\s*lcredit=.*'
        'dcredit=-1'                                                = '^\s*dcredit\s*=\s*(?!-1)\d*$|#\s*dcredit=.*'
        'difok=8'                                                   = '^\s*difok\s*=\s*(-|)[0-7]$|#\s*difok\s*=.*|difok\s+=\s+.*' # Org
        'PASS_MIN_DAYS 1'                                           = '^\s*PASS_MIN_DAYS\s*[0]*$|#\s*PASS_MIN_DAYS.*' # Org
        'PASS_MAX_DAYS 60'                                          = '^\s*PASS_MAX_DAYS\s*([0-9]|[1-5][0-9])$|#\s*PASS_MAX_DAYS.*' # Org
        'minlen=15'                                                 = '^\s*minlen\s*=\s*([0-9]|[1][1-4])$|#\s*minlen.*' # Org
        'dictcheck=1'                                               = '^\s*dictcheck\s*=\s*((?!1)|[1]\d+)\d*$|#\s*dictcheck.*'
        'enforcing = 1'                                             = '^\s*enforcing\s*=\s*((?!1)|[1]\d+)\d*$|#\s*enforcing.*'
        'ocredit=-1'                                                = '^\s*ocredit\s*=\s*(?!-1)\d*$|#\s*ocredit=.*'
        '* hard maxlogins 10'                                       = '^\s*\*\s*hard\s*maxlogins\s*([1][1-9]|[2-9]\d+|[1-9][0-9]\d+)$|^#\s*\*\s*hard\s*maxlogins.*'
        'TMOUT=900'                                                 = '^\s*TMOUT\s*=\s*[0-8]?[0-9]?[0-9]?$|^#\s*TMOUT.*' # Org
        'readonly TMOUT'                                            = '^\s*readonly\s+(?!TMOUT\b).*$|^\s*#\s*readonly.*$' # Org
        'export TMOUT'                                              = '^\s*export\s+(?!TMOUT\b).*$|^\s*#\s*export.*$' # Org
        'ClientAliveInterval 600'                                   = '^\s*ClientAliveInterval\s*[0-5]?[0-9]?[0-9]?\s*$|^#\s*ClientAliveInterval.*|^\s*ClientAliveInterval\s*$'
        'Protocol 2'                                                = '^\s*Protocol\s*([0-1]|[3-9]|\d{2,})\s*$|#\s*Protocol.*|^\s*Protocol\s*$'
        'ClientAliveCountMax 1'                                     = '^\s*ClientAliveCountMax\s*([0]|[2-9]|\d{2,})\s*$|#\s*ClientAliveCountMax.*|^\s*ClientAliveCountMax\s*$'
        'PermitEmptyPasswords no'                                   = '^\s*PermitEmptyPasswords\s*((?!no\b).)*$|^#\s*PermitEmptyPasswords.*$|^\s*PermitEmptyPasswords\s*$'
        'PermitUserEnvironment no'                                  = '^\s*PermitUserEnvironment\s*((?!no\b).)*$|^#\s*PermitUserEnvironment.*$|^\s*PermitUserEnvironment\s*$'
        'UMASK 077'                                                 = '^\s*UMASK\s*(?!077\b)\d*\s*$|^#\s*UMASK.*'
        '#Protocol 1,2' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S chmod -F auid>=1000 -F auid!=4294967295 -k perm_mod' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S chown -F auid>=1000 -F auid!=4294967295 -k perm_mod' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S creat -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S creat F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S create_module -k module-change' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S delete_module -k module-change' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S execve -C gid!=egid -F egid=0 -k setgid' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S execve -C uid!=euid -F euid=0 -k setuid' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S fchmod -F auid>=1000 -F auid!=4294967295 -k perm_mod' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S fchmodat -F auid>=1000 -F auid!=4294967295 -k perm_mod' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S fchown -F auid>=1000 -F auid!=4294967295 -k perm_mod' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S fchownat -F auid>=1000 -F auid!=4294967295 -k perm_mod' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S finit_module -k module-change' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S fremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S fsetxattr -F auid>=1000 -F auid!=4294967295 -k perm_mod' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S ftruncate -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S ftruncate -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S init_module -k module-change' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S lchown -F auid>=1000 -F auid!=4294967295 -k perm_mod' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S lremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S lsetxattr -F auid>=1000 -F auid!=4294967295 -k perm_mod' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S mount -F auid>=1000 -F auid!=4294967295 -k privileged-mount' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S open -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S open -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S open_by_handle_at -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S open_by_handle_at -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S openat -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S openat -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S removexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S rename -F auid>=1000 -F auid!=4294967295 -k delete' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S renameat -F auid>=1000 -F auid!=4294967295 -k delete' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S rmdir -F auid>=1000 -F auid!=4294967295 -k delete' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S setxattr -F auid>=1000 -F auid!=4294967295 -k perm_mod' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S truncate -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S truncate -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S unlink -F auid>=1000 -F auid!=4294967295 -k delete' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b32 -S unlinkat -F auid>=1000 -F auid!=4294967295 -k delete' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S chmod -F auid>=1000 -F auid!=4294967295 -k perm_mod' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S chown -F auid>=1000 -F auid!=4294967295 -k perm_mod' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S creat -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S creat -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S create_module -k module-change' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S delete_module -k module-change' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S execve -C gid!=egid -F egid=0 -k setgid' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S execve -C uid!=euid -F euid=0 -k setuid' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S fchmod -F auid>=1000 -F auid!=4294967295 -k perm_mod' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S fchmodat -F auid>=1000 -F auid!=4294967295 -k perm_mod' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S fchown -F auid>=1000 -F auid!=4294967295 -k perm_mod' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S fchownat -F auid>=1000 -F auid!=4294967295 -k perm_mod' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S finit_module -k module-change' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S fremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S fsetxattr -F auid>=1000 -F auid!=4294967295 -k perm_mod' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S ftruncate -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S ftruncate -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S init_module -k module-change' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S lchown -F auid>=1000 -F auid!=4294967295 -k perm_mod' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S lremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S lsetxattr -F auid>=1000 -F auid!=4294967295 -k perm_mod' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S mount -F auid>=1000 -F auid!=4294967295 -k privileged-mount' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S open -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S open -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S open_by_handle_at -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S open_by_handle_at -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S openat -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S openat -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S removexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S rename -F auid>=1000 -F auid!=4294967295 -k delete' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S renameat -F auid>=1000 -F auid!=4294967295 -k delete' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S rmdir -F auid>=1000 -F auid!=4294967295 -k delete' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S setxattr -F auid>=1000 -F auid!=4294967295 -k perm_mod' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S truncate -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S truncate -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S unlink -F auid>=1000 -F auid!=4294967295 -k delete' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F arch=b64 -S unlinkat -F auid>=1000 -F auid!=4294967295 -k delete' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F path=/usr/bin/chage -F auid>=1000 -F auid!=4294967295 -k privileged-passwd' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F path=/usr/bin/chcon -F auid>=1000 -F auid!=4294967295 -k privileged-priv_change' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F path=/usr/bin/chsh -F auid>=1000 -F auid!=4294967295 -k privileged-priv_change' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F path=/usr/bin/crontab -F auid>=1000 -F auid!=4294967295 -k privileged-cron' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F path=/usr/bin/gpasswd -F auid>=1000 -F auid!=4294967295 -k privileged-passwd' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F path=/usr/bin/mount -F auid>=1000 -F auid!=4294967295 -k privileged-mount' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F path=/usr/bin/newgrp -F auid>=1000 -F auid!=4294967295 -k privileged-priv_change' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F path=/usr/bin/passwd -F auid>=1000 -F auid!=4294967295 -k privileged-passwd' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F path=/usr/bin/su -F auid>=1000 -F auid!=4294967295 -k privileged-priv_change' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F path=/usr/bin/sudo -F auid>=1000 -F auid!=4294967295 -k privileged-priv_change' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F path=/usr/bin/umount -F auid>=1000 -F auid!=4294967295 -k privileged-mount' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F path=/usr/libexec/openssh/ssh-keysign -F auid>=1000 -F auid!=4294967295 -k privileged-ssh' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F path=/usr/sbin/pam_timestamp_check -F auid>=1000 -F auid!=4294967295 -k privileged-pam' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F path=/usr/sbin/postdrop -F auid>=1000 -F auid!=4294967295 -k privileged-postfix' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F path=/usr/sbin/postqueue -F auid>=1000 -F auid!=4294967295 -k privileged-postfix' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F path=/usr/sbin/semanage -F auid>=1000 -F auid!=4294967295 -k privileged-priv_change' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F path=/usr/sbin/setfiles -F auid>=1000 -F auid!=4294967295 -k privileged-priv_change' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F path=/usr/sbin/setsebool -F auid>=1000 -F auid!=4294967295 -k privileged-priv_change' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F path=/usr/sbin/unix_chkpwd -F auid>=1000 -F auid!=4294967295 -k privileged-passwd' = 'TestDoesNotContainPatternValueTBR'
        '-a always,exit -F path=/usr/sbin/userhelper -F auid>=1000 -F auid!=4294967295 -k privileged-passwd' = 'TestDoesNotContainPatternValueTBR'
        'action_mail_acct = root' = 'TestDoesNotContainPatternValueTBR'
        'AutomaticLoginEnable=false' = 'TestDoesNotContainPatternValueTBR'
        'banner /etc/issue' = 'TestDoesNotContainPatternValueTBR'
        'banner-message-enable=true' = 'TestDoesNotContainPatternValueTBR'
        'cert_policy = ca, ocsp_on, signature;' = 'TestDoesNotContainPatternValueTBR'
        'Ciphers aes128-ctr,aes192-ctr,aes256-ctr' = 'TestDoesNotContainPatternValueTBR'
        'clean_requirements_on_remove=1' = 'TestDoesNotContainPatternValueTBR'
        'ClientAliveCountMax 0' = 'TestDoesNotContainPatternValueTBR'
        'Compression delayed' = 'TestDoesNotContainPatternValueTBR'
        'CREATE_HOME yes' = 'TestDoesNotContainPatternValueTBR'
        'crypt_style = sha512' = 'TestDoesNotContainPatternValueTBR'
        'dcredit = -1' = 'TestDoesNotContainPatternValueTBR'
        'direction = out' = 'TestDoesNotContainPatternValueTBR'
        'disk_full_action = single' = 'TestDoesNotContainPatternValueTBR'
        'enable_krb5 = yes' = 'TestDoesNotContainPatternValueTBR'
        'ENCRYPT_METHOD SHA512' = 'TestDoesNotContainPatternValueTBR'
        'ExecStart=-/bin/sh -c "/usr/sbin/sulogin; /usr/bin/systemctl --fail --no-block default"' = 'TestDoesNotContainPatternValueTBR'
        'format = string' = 'TestDoesNotContainPatternValueTBR'
        'gpgcheck=1' = 'TestDoesNotContainPatternValueTBR'
        'GSSAPIAuthentication no' = 'TestDoesNotContainPatternValueTBR'
        'HostbasedAuthentication no' = 'TestDoesNotContainPatternValueTBR'
        'idle-activation-enabled=true' = 'TestDoesNotContainPatternValueTBR'
        'IgnoreRhosts yes' = 'TestDoesNotContainPatternValueTBR'
        'IgnoreUserKnownHosts yes' = 'TestDoesNotContainPatternValueTBR'
        'INACTIVE=0' = 'TestDoesNotContainPatternValueTBR'
        'KerberosAuthentication no' = 'TestDoesNotContainPatternValueTBR'
        'lcredit = -1' = 'TestDoesNotContainPatternValueTBR'
        'localpkg_gpgcheck=1' = 'TestDoesNotContainPatternValueTBR'
        'lock-enabled=true' = 'TestDoesNotContainPatternValueTBR'
        'MACs hmac-sha2-256,hmac-sha2-512' = 'TestDoesNotContainPatternValueTBR'
        'maxclassrepeat = 4' = 'TestDoesNotContainPatternValueTBR'
        'maxrepeat = 3' = 'TestDoesNotContainPatternValueTBR'
        'name_format = hostname' = 'TestDoesNotContainPatternValueTBR'
        'network_failure_action = syslog' = 'TestDoesNotContainPatternValueTBR'
        'overflow_action = syslog' = 'TestDoesNotContainPatternValueTBR'
        'password substack system-auth' = 'TestDoesNotContainPatternValueTBR'
        'path = /sbin/audisp-remote' = 'TestDoesNotContainPatternValueTBR'
        'PermitRootLogin no' = 'TestDoesNotContainPatternValueTBR'
        'PrintLastLog yes' = 'TestDoesNotContainPatternValueTBR'
        'remote_server = 10.0.21.1' = 'TestDoesNotContainPatternValueTBR'
        'RhostsRSAAuthentication no' = 'TestDoesNotContainPatternValueTBR'
        'SELINUXTYPE = targeted' = 'TestDoesNotContainPatternValueTBR'
        'server_args = -s /var/lib/tftpboot' = 'TestDoesNotContainPatternValueTBR'
        'space_left = 225' = 'TestDoesNotContainPatternValueTBR'
        'space_left_action = email' = 'TestDoesNotContainPatternValueTBR'
        'StrictModes yes' = 'TestDoesNotContainPatternValueTBR'
        'There should be at least three lines returned.' = 'TestDoesNotContainPatternValueTBR'
        'This command will return the banner keyword and the name of the file that contains the ssh banner (in this case "/etc/issue").' = 'TestDoesNotContainPatternValueTBR'
        'TimedLoginEnable=false' = 'TestDoesNotContainPatternValueTBR'
        'type = always' = 'TestDoesNotContainPatternValueTBR'
        'ucredit = -1' = 'TestDoesNotContainPatternValueTBR'
        'UsePrivilegeSeparation sandbox' = 'TestDoesNotContainPatternValueTBR'
        '-w /etc/group -p wa -k identity' = 'TestDoesNotContainPatternValueTBR'
        '-w /etc/gshadow -p wa -k identity' = 'TestDoesNotContainPatternValueTBR'
        '-w /etc/passwd -p wa -k identity' = 'TestDoesNotContainPatternValueTBR'
        '-w /etc/security/opasswd -p wa -k identity' = 'TestDoesNotContainPatternValueTBR'
        '-w /etc/shadow -p wa -k identity' = 'TestDoesNotContainPatternValueTBR'
        '-w /etc/sudoers -p wa -k privileged-actions # grep -i "/etc/sudoers.d/" /etc/audit/audit.rules -w /etc/sudoers.d/ -p wa -k privileged-actions' = 'TestDoesNotContainPatternValueTBR'
        '-w /usr/bin/kmod -p x -F auid!=4294967295 -k module-change' = 'TestDoesNotContainPatternValueTBR'
        '-w /var/log/lastlog -p wa -k logins' = 'TestDoesNotContainPatternValueTBR'
        '-w /var/run/faillock -p wa -k logins' = 'TestDoesNotContainPatternValueTBR'
        'X11Forwarding yes' = 'TestDoesNotContainPatternValueTBR'
    }
}
